import type { Metadata } from 'next'
import { dmSans, libre } from '@/utils'
import '@/styles/globals.scss'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${dmSans.variable} ${libre.variable}`}>
      <body>{children}</body>
    </html>
  )
}
